language: python
dist: bionic

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-django32

    - python: 3.8
      env: TOXENV=py38-django32
    - python: 3.8
      env: TOXENV=py38-django40

    - python: 3.9
      env: TOXENV=py39-django32
    - python: 3.9
      env: TOXENV=py39-django40

    - python: 3.10
      env: TOXENV=py310-django32
    - python: 3.10
      env: TOXENV=py310-django40

install: pip install --quiet --upgrade pip tox

# command to run tests
script: tox

after_script:
  - if [ $TOXENV == "py310-django40" ]; then
      pip install --quiet coveralls;
      coveralls;
    fi
